name: fitness_tracker_app
description: A new Flutter project.

# The following line prevents your package from being accidentally published to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  provider: ^6.1.1
  sqflite: ^2.3.2
  fl_chart: ^0.66.2
  flutter_native_splash: ^2.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/  # Ensure you have this image in your project under the assets directory

flutter_native_splash:
  color: "#42a5f5"
  image: assets/splash.png
  android: true
  ios: true
